# Find Place v1
GET https://maps.googleapis.com/maps/api/place/textsearch/json
  ?fields=name%2Cformatted_address%2Crating
  &query=restaurants%20in%20paris%20france
  &type=restaurant
  &key=KEY

###

# Text Search v2
POST https://places.googleapis.com/v1/places:searchText
Content-Type: application/json
X-Goog-Api-Key: KEY
X-Goog-FieldMask: places.displayName,places.formattedAddress,places.rating

{
  "textQuery" : "restaurants in paris france",
  "includedType": "restaurant"
}

###

# Query Autocomplete v1
GET https://maps.googleapis.com/maps/api/place/queryautocomplete/json
  ?input=pizza%20near%20par
  &key=KEY

###

# Find Place v2
POST https://places.googleapis.com/v1/places:autocomplete
Content-Type: application/json
X-Goog-Api-Key: KEY

{
  "input" : "pizza near par",
  "includeQueryPredictions": true
}
